/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SET 0x1
#define UNSET 0x0
#define u32 uint32_t
#define BIT(x) (0x1 << x)
#define MEM_MAP_REG(base,offset) ((base) + (offset))




#define GPIOD_BASE			0x40020C00

#define GPIOx_ODR_OFF 		0x14
#define GPIOx_MODER_OFF 	0x0
#define RCC_BASE 			0x40023800
#define RCC_AHB1ENR_OFF 	0x30



#define MODER_CONF_INPUT 0x00
#define MODER_CONF_GENERAL_PURPOSE_OUTPUT 0x01
#define MODER_CONF_ALTERNATE_FUNCTION 0x10
#define MODER_CONF_ANALOG_MODE 	0x11

typedef struct GPIOx_ODR
{
	u32 ODR00 : 1;
	u32 ODR01 : 1;
	u32 ODR02 : 1;
	u32 ODR03 : 1;
	u32 ODR04 : 1;
	u32 ODR05 : 1;
	u32 ODR06 : 1;
	u32 ODR07 : 1;
	u32 ODR08 : 1;
	u32 ODR09 : 1;
	u32 ODR10 : 1;
	u32 ODR11 : 1;
	u32 ODR12 : 1;
	u32 ODR13 : 1;
	u32 ODR14 : 1;
	u32 ODR15 : 1;
	u32 Reserved : 16;
}GPIOx_ODR;

typedef struct GPIOx_MODER
{
	u32 MODER00 : 2;
	u32 MODER01 : 2;
	u32 MODER02 : 2;
	u32 MODER03 : 2;
	u32 MODER04 : 2;
	u32 MODER05 : 2;
	u32 MODER06 : 2;
	u32 MODER07 : 2;
	u32 MODER08 : 2;
	u32 MODER09 : 2;
	u32 MODER10 : 2;
	u32 MODER11 : 2;
	u32 MODER12 : 2;
	u32 MODER13 : 2;
	u32 MODER14 : 2;
	u32 MODER15 : 2;
}GPIOx_MODER;

typedef struct RCC_AHB1ENR
{
	u32 GPIOAEN		:1;
	u32 GPIOBEN		:1;
	u32 GPIOCEN		:1;
	u32 GPIODEN		:1;
	u32 GPIOEEN		:1;
	u32 GPIOFEN		:1;
	u32 GPIOGEN		:1;
	u32 GPIOHEN		:1;
	u32 GPIOIEN		:1;
	u32 Reserved0	:3;
	u32 CRCEN		:1;
	u32 Reserved1	:5;
	u32 BKPSRAMEN	:1;
	u32 Reserved2	:1;
	u32 CCMDATARAMEN:1;
	u32 DMA1EN		:1;
	u32 DMA2EN		:1;
	u32 Reserved3	:2;
	u32 ETHMACEN	:1;
	u32 ETHMACTXEN	:1;
	u32 ETHMACRXEN	:1;
	u32 ETHMACPTPEN	:1;
	u32 OTGHSEN		:1;
	u32 OTGHSULPIEN	:1;
	u32 Reserved4	:1;
}RCC_AHB1ENR;



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/* Loop forever */
	RCC_AHB1ENR* prcc_ahb1 = (RCC_AHB1ENR*)MEM_MAP_REG(RCC_BASE,RCC_AHB1ENR_OFF);
	GPIOx_MODER* pgpiod_mode = (GPIOx_MODER*) MEM_MAP_REG(GPIOD_BASE,GPIOx_MODER_OFF);
	GPIOx_ODR* pgpiod_odr = (GPIOx_ODR*) MEM_MAP_REG(GPIOD_BASE,GPIOx_ODR_OFF);
	prcc_ahb1->GPIODEN = SET;
	pgpiod_mode->MODER12 = MODER_CONF_GENERAL_PURPOSE_OUTPUT;
	pgpiod_odr->ODR12 = SET;

	for(;;);
}
